# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Student_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Student_Dialog(object):
    def setupUi(self, Student_Dialog):
        Student_Dialog.setObjectName("Student_Dialog")
        Student_Dialog.resize(707, 639)
        Student_Dialog.setStyleSheet("QWidget {\n"
"    background-color: #73C2FB; /* Ice Blue*/\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}")
        self.Welcome = QtWidgets.QLineEdit(Student_Dialog)
        self.Welcome.setGeometry(QtCore.QRect(180, 80, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Welcome.setFont(font)
        self.Welcome.setStyleSheet("QLineEdit\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}")
        self.Welcome.setObjectName("Welcome")
        self.label = QtWidgets.QLabel(Student_Dialog)
        self.label.setGeometry(QtCore.QRect(300, 0, 81, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Spartan_Ride_App/SpartanLogo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Student_Dialog)
        self.label_2.setGeometry(QtCore.QRect(640, 10, 51, 51))
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Images/person.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.student_name = QtWidgets.QLabel(Student_Dialog)
        self.student_name.setGeometry(QtCore.QRect(490, 10, 60, 16))
        self.student_name.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}")
        self.student_name.setObjectName("student_name")
        self.Balamce = QtWidgets.QLabel(Student_Dialog)
        self.Balamce.setGeometry(QtCore.QRect(490, 40, 60, 16))
        self.Balamce.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}")
        self.Balamce.setObjectName("Balamce")
        self.line = QtWidgets.QFrame(Student_Dialog)
        self.line.setGeometry(QtCore.QRect(0, 125, 701, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Student_pushbuttons = QtWidgets.QGroupBox(Student_Dialog)
        self.Student_pushbuttons.setGeometry(QtCore.QRect(0, 150, 701, 51))
        self.Student_pushbuttons.setTitle("")
        self.Student_pushbuttons.setObjectName("Student_pushbuttons")
        self.Wallet = QtWidgets.QPushButton(self.Student_pushbuttons)
        self.Wallet.setGeometry(QtCore.QRect(560, 10, 113, 32))
        self.Wallet.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Wallet.setObjectName("Wallet")
        self.RideHistory = QtWidgets.QPushButton(self.Student_pushbuttons)
        self.RideHistory.setGeometry(QtCore.QRect(390, 10, 113, 32))
        self.RideHistory.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.RideHistory.setObjectName("RideHistory")
        self.BookaRide = QtWidgets.QPushButton(self.Student_pushbuttons)
        self.BookaRide.setGeometry(QtCore.QRect(210, 10, 113, 32))
        self.BookaRide.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.BookaRide.setObjectName("BookaRide")
        self.Profile = QtWidgets.QPushButton(self.Student_pushbuttons)
        self.Profile.setGeometry(QtCore.QRect(30, 10, 113, 32))
        self.Profile.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Profile.setObjectName("Profile")
        self.Feedback = QtWidgets.QPushButton(Student_Dialog)
        self.Feedback.setGeometry(QtCore.QRect(10, 590, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setBold(True)
        font.setWeight(75)
        self.Feedback.setFont(font)
        self.Feedback.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Feedback.setObjectName("Feedback")
        self.SignOut = QtWidgets.QPushButton(Student_Dialog)
        self.SignOut.setGeometry(QtCore.QRect(610, 590, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setBold(True)
        font.setWeight(75)
        self.SignOut.setFont(font)
        self.SignOut.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.SignOut.setObjectName("SignOut")
        self.Schedule = QtWidgets.QLabel(Student_Dialog)
        self.Schedule.setGeometry(QtCore.QRect(30, 210, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Schedule.setFont(font)
        self.Schedule.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}")
        self.Schedule.setObjectName("Schedule")
        self.calendarWidget = QtWidgets.QCalendarWidget(Student_Dialog)
        self.calendarWidget.setGeometry(QtCore.QRect(20, 270, 391, 281))
        self.calendarWidget.setAutoFillBackground(False)
        self.calendarWidget.setStyleSheet("QCalendarWidget {\n"
"    background-color: #E6F2FF; /* Light blue bg */\n"
"   \n"
"    border-radius: 10px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton {\n"
"    color: #0B1D3A; /* Dark navy */\n"
"    font-weight: bold;\n"
"    background-color: ;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QCalendarWidget QMenu {\n"
"    background-color: #FFFACD;\n"
"}\n"
"\n"
"QCalendarWidget QSpinBox {\n"
"    width: 60px;\n"
"}\n"
"")
        self.calendarWidget.setSelectedDate(QtCore.QDate(2025, 4, 9))
        self.calendarWidget.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Student_Dialog)
        self.dateTimeEdit.setGeometry(QtCore.QRect(220, 230, 194, 24))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_3 = QtWidgets.QLabel(Student_Dialog)
        self.label_3.setGeometry(QtCore.QRect(460, 240, 221, 311))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../Images/ChatGPT Image Apr 21, 2025, 10_35_04 PM.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Student_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Student_Dialog)

    def retranslateUi(self, Student_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Student_Dialog.setWindowTitle(_translate("Student_Dialog", "Dialog"))
        self.Welcome.setText(_translate("Student_Dialog", "Welcome to Spartan Ride"))
        self.student_name.setText(_translate("Student_Dialog", "Name"))
        self.Balamce.setText(_translate("Student_Dialog", "Balance"))
        self.Wallet.setText(_translate("Student_Dialog", "Wallet"))
        self.RideHistory.setText(_translate("Student_Dialog", "Ride History"))
        self.BookaRide.setText(_translate("Student_Dialog", "Book Ride"))
        self.Profile.setText(_translate("Student_Dialog", "Profile"))
        self.Feedback.setText(_translate("Student_Dialog", "Feedback"))
        self.SignOut.setText(_translate("Student_Dialog", "Sign Out"))
        self.Schedule.setText(_translate("Student_Dialog", "My Schedule"))
