# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Student_RouteDetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Student_Dialog(object):
    def setupUi(self, Student_Dialog):
        Student_Dialog.setObjectName("Student_Dialog")
        Student_Dialog.resize(707, 639)
        Student_Dialog.setStyleSheet("QWidget {\n"
"    background-color: #73C2FB; /* Ice Blue*/\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}")
        self.Welcome = QtWidgets.QLineEdit(Student_Dialog)
        self.Welcome.setGeometry(QtCore.QRect(180, 80, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Welcome.setFont(font)
        self.Welcome.setStyleSheet("QLineEdit\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}")
        self.Welcome.setObjectName("Welcome")
        self.label = QtWidgets.QLabel(Student_Dialog)
        self.label.setGeometry(QtCore.QRect(300, 0, 81, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Spartan_Ride_App/SpartanLogo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Student_Dialog)
        self.label_2.setGeometry(QtCore.QRect(640, 10, 51, 51))
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Images/person.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.student_name = QtWidgets.QLabel(Student_Dialog)
        self.student_name.setGeometry(QtCore.QRect(490, 10, 60, 16))
        self.student_name.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}")
        self.student_name.setObjectName("student_name")
        self.Balamce = QtWidgets.QLabel(Student_Dialog)
        self.Balamce.setGeometry(QtCore.QRect(490, 40, 60, 16))
        self.Balamce.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}")
        self.Balamce.setObjectName("Balamce")
        self.line = QtWidgets.QFrame(Student_Dialog)
        self.line.setGeometry(QtCore.QRect(0, 125, 701, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.SignOut = QtWidgets.QPushButton(Student_Dialog)
        self.SignOut.setGeometry(QtCore.QRect(610, 590, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setBold(True)
        font.setWeight(75)
        self.SignOut.setFont(font)
        self.SignOut.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.SignOut.setObjectName("SignOut")
        self.Route_Label = QtWidgets.QLabel(Student_Dialog)
        self.Route_Label.setGeometry(QtCore.QRect(30, 160, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Route_Label.setFont(font)
        self.Route_Label.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}")
        self.Route_Label.setObjectName("Route_Label")
        self.Time_Label_2 = QtWidgets.QLabel(Student_Dialog)
        self.Time_Label_2.setGeometry(QtCore.QRect(30, 220, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Time_Label_2.setFont(font)
        self.Time_Label_2.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}")
        self.Time_Label_2.setObjectName("Time_Label_2")
        self.Day_Labe = QtWidgets.QLabel(Student_Dialog)
        self.Day_Labe.setGeometry(QtCore.QRect(380, 160, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Day_Labe.setFont(font)
        self.Day_Labe.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"}")
        self.Day_Labe.setObjectName("Day_Labe")
        self.timeEdit = QtWidgets.QTimeEdit(Student_Dialog)
        self.timeEdit.setGeometry(QtCore.QRect(140, 230, 118, 24))
        self.timeEdit.setStyleSheet("QtimeEdit {\n"
"    background-color: white;       /* Yellow background */\n"
"    color: blue;                    /* Blue text */\n"
"    border: 2px solid blue;          /* Blue border */\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background-color: blue;          /* Blue dropdown button */\n"
"    width: 30px;\n"
"    border-left: 1px solid yellow;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;                     /* Remove default arrow */\n"
"    width: 0;\n"
"    height: 0;\n"
"    border-left: 8px solid transparent;\n"
"    border-right: 8px solid transparent;\n"
"    border-top: 10px solid  white;    /* Custom yellow arrow */\n"
"}\n"
"")
        self.timeEdit.setObjectName("timeEdit")
        self.BookRide_Label = QtWidgets.QPushButton(Student_Dialog)
        self.BookRide_Label.setGeometry(QtCore.QRect(260, 300, 171, 51))
        self.BookRide_Label.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.BookRide_Label.setObjectName("BookRide_Label")
        self.comboBox = QtWidgets.QComboBox(Student_Dialog)
        self.comboBox.setGeometry(QtCore.QRect(140, 170, 121, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Student_Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(470, 160, 104, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")

        self.retranslateUi(Student_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Student_Dialog)

    def retranslateUi(self, Student_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Student_Dialog.setWindowTitle(_translate("Student_Dialog", "Dialog"))
        self.Welcome.setText(_translate("Student_Dialog", "Welcome to Spartan Ride"))
        self.student_name.setText(_translate("Student_Dialog", "Name"))
        self.Balamce.setText(_translate("Student_Dialog", "Balance"))
        self.SignOut.setText(_translate("Student_Dialog", "Sign Out"))
        self.Route_Label.setText(_translate("Student_Dialog", "Route "))
        self.Time_Label_2.setText(_translate("Student_Dialog", "Time"))
        self.Day_Labe.setText(_translate("Student_Dialog", "Day"))
        self.BookRide_Label.setText(_translate("Student_Dialog", "BOOK RIDE"))
        self.comboBox.setItemText(0, _translate("Student_Dialog", "Yellow Line"))
        self.comboBox.setItemText(1, _translate("Student_Dialog", "Orange Line"))
        self.comboBox.setItemText(2, _translate("Student_Dialog", "Blue Line"))
        self.comboBox.setItemText(3, _translate("Student_Dialog", "Green Line"))
        self.comboBox_2.setItemText(0, _translate("Student_Dialog", "Monday"))
        self.comboBox_2.setItemText(1, _translate("Student_Dialog", "Tuesday"))
        self.comboBox_2.setItemText(2, _translate("Student_Dialog", "Wednesday"))
        self.comboBox_2.setItemText(3, _translate("Student_Dialog", "Thursday"))
        self.comboBox_2.setItemText(4, _translate("Student_Dialog", "Friday"))
        self.comboBox_2.setItemText(5, _translate("Student_Dialog", "Saturday"))
        self.comboBox_2.setItemText(6, _translate("Student_Dialog", "Sunday"))
