# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Driver_MyProfile.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignUp_Dialog(object):
    def setupUi(self, SignUp_Dialog):
        SignUp_Dialog.setObjectName("SignUp_Dialog")
        SignUp_Dialog.resize(793, 545)
        SignUp_Dialog.setStyleSheet("QWidget {\n"
"    background-color: #73C2FB; /* Ice Blue*/\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}")
        self.Login = QtWidgets.QPushButton(SignUp_Dialog)
        self.Login.setGeometry(QtCore.QRect(60, 120, 113, 41))
        self.Login.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Login.setObjectName("Login")
        self.Name = QtWidgets.QLabel(SignUp_Dialog)
        self.Name.setGeometry(QtCore.QRect(50, 190, 151, 31))
        self.Name.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Name.setTextFormat(QtCore.Qt.RichText)
        self.Name.setScaledContents(True)
        self.Name.setObjectName("Name")
        self.EmailID = QtWidgets.QLabel(SignUp_Dialog)
        self.EmailID.setGeometry(QtCore.QRect(50, 250, 91, 16))
        self.EmailID.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.EmailID.setTextFormat(QtCore.Qt.RichText)
        self.EmailID.setScaledContents(True)
        self.EmailID.setObjectName("EmailID")
        self.Submit = QtWidgets.QPushButton(SignUp_Dialog)
        self.Submit.setGeometry(QtCore.QRect(470, 460, 121, 41))
        self.Submit.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Submit.setObjectName("Submit")
        self.Login_2 = QtWidgets.QPushButton(SignUp_Dialog)
        self.Login_2.setGeometry(QtCore.QRect(260, 120, 113, 41))
        self.Login_2.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Login_2.setObjectName("Login_2")
        self.Login_3 = QtWidgets.QPushButton(SignUp_Dialog)
        self.Login_3.setGeometry(QtCore.QRect(440, 120, 113, 41))
        self.Login_3.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Login_3.setObjectName("Login_3")
        self.Login_4 = QtWidgets.QPushButton(SignUp_Dialog)
        self.Login_4.setGeometry(QtCore.QRect(630, 120, 113, 41))
        self.Login_4.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Login_4.setObjectName("Login_4")
        self.EmailID_2 = QtWidgets.QLabel(SignUp_Dialog)
        self.EmailID_2.setGeometry(QtCore.QRect(50, 290, 91, 16))
        self.EmailID_2.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.EmailID_2.setTextFormat(QtCore.Qt.RichText)
        self.EmailID_2.setScaledContents(True)
        self.EmailID_2.setObjectName("EmailID_2")
        self.EmailID_3 = QtWidgets.QLabel(SignUp_Dialog)
        self.EmailID_3.setGeometry(QtCore.QRect(50, 330, 101, 16))
        self.EmailID_3.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.EmailID_3.setTextFormat(QtCore.Qt.RichText)
        self.EmailID_3.setScaledContents(True)
        self.EmailID_3.setObjectName("EmailID_3")
        self.EmailID_4 = QtWidgets.QLabel(SignUp_Dialog)
        self.EmailID_4.setGeometry(QtCore.QRect(50, 370, 101, 16))
        self.EmailID_4.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.EmailID_4.setTextFormat(QtCore.Qt.RichText)
        self.EmailID_4.setScaledContents(True)
        self.EmailID_4.setObjectName("EmailID_4")
        self.lineEdit = QtWidgets.QLineEdit(SignUp_Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(190, 250, 231, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(SignUp_Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 290, 231, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(SignUp_Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(190, 330, 231, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(SignUp_Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(190, 370, 231, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.Submit_2 = QtWidgets.QPushButton(SignUp_Dialog)
        self.Submit_2.setGeometry(QtCore.QRect(630, 460, 121, 41))
        self.Submit_2.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Submit_2.setObjectName("Submit_2")
        self.Name_2 = QtWidgets.QLabel(SignUp_Dialog)
        self.Name_2.setGeometry(QtCore.QRect(270, 70, 241, 31))
        self.Name_2.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Name_2.setTextFormat(QtCore.Qt.RichText)
        self.Name_2.setScaledContents(True)
        self.Name_2.setObjectName("Name_2")
        self.EmailID_7 = QtWidgets.QLabel(SignUp_Dialog)
        self.EmailID_7.setGeometry(QtCore.QRect(50, 410, 121, 16))
        self.EmailID_7.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.EmailID_7.setTextFormat(QtCore.Qt.RichText)
        self.EmailID_7.setScaledContents(True)
        self.EmailID_7.setObjectName("EmailID_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(SignUp_Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(190, 410, 231, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label = QtWidgets.QLabel(SignUp_Dialog)
        self.label.setGeometry(QtCore.QRect(350, 10, 61, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images/SpartanLogo_small.png"))
        self.label.setObjectName("label")
        self.EmailID_5 = QtWidgets.QLabel(SignUp_Dialog)
        self.EmailID_5.setGeometry(QtCore.QRect(590, 20, 91, 16))
        self.EmailID_5.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.EmailID_5.setTextFormat(QtCore.Qt.RichText)
        self.EmailID_5.setScaledContents(True)
        self.EmailID_5.setObjectName("EmailID_5")
        self.EmailID_6 = QtWidgets.QLabel(SignUp_Dialog)
        self.EmailID_6.setGeometry(QtCore.QRect(590, 50, 91, 16))
        self.EmailID_6.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.EmailID_6.setTextFormat(QtCore.Qt.RichText)
        self.EmailID_6.setScaledContents(True)
        self.EmailID_6.setObjectName("EmailID_6")
        self.label_3 = QtWidgets.QLabel(SignUp_Dialog)
        self.label_3.setGeometry(QtCore.QRect(670, 50, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(SignUp_Dialog)
        self.label_2.setGeometry(QtCore.QRect(670, 20, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(SignUp_Dialog)
        self.label_4.setGeometry(QtCore.QRect(480, 210, 241, 231))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Driver_Image.png"))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(SignUp_Dialog)
        QtCore.QMetaObject.connectSlotsByName(SignUp_Dialog)

    def retranslateUi(self, SignUp_Dialog):
        _translate = QtCore.QCoreApplication.translate
        SignUp_Dialog.setWindowTitle(_translate("SignUp_Dialog", "Dialog"))
        self.Login.setText(_translate("SignUp_Dialog", "My Profile"))
        self.Name.setText(_translate("SignUp_Dialog", "<html><head/><body><p><span style=\" font-size:24pt;\">My Profile</span></p></body></html>"))
        self.EmailID.setText(_translate("SignUp_Dialog", "Driver Name"))
        self.Submit.setText(_translate("SignUp_Dialog", "Edit"))
        self.Login_2.setText(_translate("SignUp_Dialog", "My Routes"))
        self.Login_3.setText(_translate("SignUp_Dialog", "My Log"))
        self.Login_4.setText(_translate("SignUp_Dialog", "Notifications"))
        self.EmailID_2.setText(_translate("SignUp_Dialog", "Driver ID"))
        self.EmailID_3.setText(_translate("SignUp_Dialog", "Mobile Phone"))
        self.EmailID_4.setText(_translate("SignUp_Dialog", "e-mail Adress"))
        self.Submit_2.setText(_translate("SignUp_Dialog", "Save"))
        self.Name_2.setText(_translate("SignUp_Dialog", "<html><head/><body><p><span style=\" font-size:18pt;\">Welcome to Spartan Ride</span></p></body></html>"))
        self.EmailID_7.setText(_translate("SignUp_Dialog", "License Number"))
        self.EmailID_5.setText(_translate("SignUp_Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:400; color:#0c0805;\">Name</span></p></body></html>"))
        self.EmailID_6.setText(_translate("SignUp_Dialog", "<html><head/><body><p><span style=\" font-weight:400; color:#0b0905;\">Date</span></p></body></html>"))
        self.label_3.setText(_translate("SignUp_Dialog", "Apr 25, 2025"))
        self.label_2.setText(_translate("SignUp_Dialog", "John Stein"))
