# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_Page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginPage(object):
    def setupUi(self, LoginPage):
        LoginPage.setObjectName("LoginPage")
        LoginPage.setEnabled(True)
        LoginPage.resize(411, 550)
        LoginPage.setStyleSheet("QWidget {\n"
"    background-color: #73C2FB; /* Ice Blue*/\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QFont{\n"
"    font-size: 3;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(LoginPage)
        self.centralwidget.setObjectName("centralwidget")
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setEnabled(True)
        self.Logo.setGeometry(QtCore.QRect(130, 0, 121, 91))
        self.Logo.setAutoFillBackground(False)
        self.Logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Logo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("Images/SpartanLogo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setWordWrap(True)
        self.Logo.setObjectName("Logo")
        self.SJSU_id_label = QtWidgets.QLabel(self.centralwidget)
        self.SJSU_id_label.setGeometry(QtCore.QRect(20, 210, 121, 16))
        self.SJSU_id_label.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.SJSU_id_label.setTextFormat(QtCore.Qt.RichText)
        self.SJSU_id_label.setScaledContents(True)
        self.SJSU_id_label.setObjectName("SJSU_id_label")
        self.EnterYourEmailUser = QtWidgets.QLineEdit(self.centralwidget)
        self.EnterYourEmailUser.setGeometry(QtCore.QRect(10, 240, 331, 31))
        self.EnterYourEmailUser.setStyleSheet("QLineEdit {\n"
"    background-color: transparent;\n"
"    border: 2px solid white;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"    color: yellow;\n"
"}")
        self.EnterYourEmailUser.setObjectName("EnterYourEmailUser")
        self.Password = QtWidgets.QLabel(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(20, 290, 111, 16))
        self.Password.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Password.setTextFormat(QtCore.Qt.RichText)
        self.Password.setScaledContents(True)
        self.Password.setObjectName("Password")
        self.Password_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Password_2.setGeometry(QtCore.QRect(10, 320, 331, 31))
        self.Password_2.setStyleSheet("QLineEdit {\n"
"    background-color: transparent;\n"
"    border: 2px solid white;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"    color: white;\n"
"}")
        self.Password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_2.setObjectName("Password_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 290, 31, 21))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("mail.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.JoinUS = QtWidgets.QLabel(self.centralwidget)
        self.JoinUS.setGeometry(QtCore.QRect(40, 160, 301, 20))
        self.JoinUS.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 16px;\n"
"}")
        self.JoinUS.setTextFormat(QtCore.Qt.RichText)
        self.JoinUS.setScaledContents(True)
        self.JoinUS.setObjectName("JoinUS")
        self.SPARTANRIDE = QtWidgets.QLabel(self.centralwidget)
        self.SPARTANRIDE.setGeometry(QtCore.QRect(60, 110, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.SPARTANRIDE.setFont(font)
        self.SPARTANRIDE.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 36px;\n"
"    font-weight: bold;\n"
"}")
        self.SPARTANRIDE.setTextFormat(QtCore.Qt.RichText)
        self.SPARTANRIDE.setScaledContents(True)
        self.SPARTANRIDE.setObjectName("SPARTANRIDE")
        self.join = QtWidgets.QPushButton(self.centralwidget)
        self.join.setEnabled(True)
        self.join.setGeometry(QtCore.QRect(120, 370, 121, 41))
        self.join.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.join.setCheckable(True)
        self.join.setChecked(True)
        self.join.setObjectName("join")
        self.roleSelector = QtWidgets.QComboBox(self.centralwidget)
        self.roleSelector.setGeometry(QtCore.QRect(30, 430, 111, 31))
        self.roleSelector.setObjectName("roleSelector")
        self.roleSelector.addItem("")
        self.roleSelector.addItem("")
        self.roleSelector.addItem("")
        self.roleSelector.addItem("")
        self.SignUp = QtWidgets.QPushButton(self.centralwidget)
        self.SignUp.setGeometry(QtCore.QRect(250, 420, 111, 41))
        self.SignUp.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.SignUp.setObjectName("SignUp")
        LoginPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 411, 24))
        self.menubar.setObjectName("menubar")
        LoginPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginPage)
        self.statusbar.setObjectName("statusbar")
        LoginPage.setStatusBar(self.statusbar)

        self.retranslateUi(LoginPage)
        QtCore.QMetaObject.connectSlotsByName(LoginPage)

    def retranslateUi(self, LoginPage):
        _translate = QtCore.QCoreApplication.translate
        LoginPage.setWindowTitle(_translate("LoginPage", "MainWindow"))
        self.SJSU_id_label.setText(_translate("LoginPage", "SJSU Id"))
        self.Password.setText(_translate("LoginPage", "Password"))
        self.JoinUS.setText(_translate("LoginPage", "Join SpartanRide for Shuttle Service"))
        self.SPARTANRIDE.setText(_translate("LoginPage", "SPARTAN RIDE"))
        self.join.setText(_translate("LoginPage", "Login"))
        self.roleSelector.setItemText(0, _translate("LoginPage", "Student"))
        self.roleSelector.setItemText(1, _translate("LoginPage", "Faculty"))
        self.roleSelector.setItemText(2, _translate("LoginPage", "Driver"))
        self.roleSelector.setItemText(3, _translate("LoginPage", "Admin"))
        self.SignUp.setText(_translate("LoginPage", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginPage = QtWidgets.QMainWindow()
    ui = Ui_LoginPage()
    ui.setupUi(LoginPage)
    LoginPage.show()
    sys.exit(app.exec_())
