# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Files/Profile_DialogBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Profile_Window_Dialog(object):
    def setupUi(self, Profile_Window_Dialog):
        Profile_Window_Dialog.setObjectName("Profile_Window_Dialog")
        Profile_Window_Dialog.resize(1050, 600)
        Profile_Window_Dialog.setStyleSheet("QWidget {\n"
"    background-color: #73C2FB; /* Ice Blue*/\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}")
        self.line = QtWidgets.QFrame(Profile_Window_Dialog)
        self.line.setGeometry(QtCore.QRect(430, 0, 20, 411))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Photo = QtWidgets.QLabel(Profile_Window_Dialog)
        self.Photo.setGeometry(QtCore.QRect(40, 10, 91, 81))
        self.Photo.setText("")
        self.Photo.setPixmap(QtGui.QPixmap("UI_Files/Images/person.png"))
        self.Photo.setScaledContents(True)
        self.Photo.setObjectName("Photo")
        self.Name_Label = QtWidgets.QLabel(Profile_Window_Dialog)
        self.Name_Label.setGeometry(QtCore.QRect(60, 100, 81, 21))
        self.Name_Label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Name_Label.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Name_Label.setWordWrap(True)
        self.Name_Label.setObjectName("Name_Label")
        self.User_id_label = QtWidgets.QLabel(Profile_Window_Dialog)
        self.User_id_label.setGeometry(QtCore.QRect(10, 150, 81, 21))
        self.User_id_label.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.User_id_label.setObjectName("User_id_label")
        self.Email_Label = QtWidgets.QLabel(Profile_Window_Dialog)
        self.Email_Label.setGeometry(QtCore.QRect(10, 200, 81, 21))
        self.Email_Label.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Email_Label.setObjectName("Email_Label")
        self.Address_label = QtWidgets.QLabel(Profile_Window_Dialog)
        self.Address_label.setGeometry(QtCore.QRect(10, 250, 81, 21))
        self.Address_label.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Address_label.setObjectName("Address_label")
        self.line_2 = QtWidgets.QFrame(Profile_Window_Dialog)
        self.line_2.setGeometry(QtCore.QRect(210, 250, 311, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.CourseName_label = QtWidgets.QLabel(Profile_Window_Dialog)
        self.CourseName_label.setGeometry(QtCore.QRect(230, 20, 121, 41))
        self.CourseName_label.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.CourseName_label.setObjectName("CourseName_label")
        self.Enrollment_Number_label = QtWidgets.QLabel(Profile_Window_Dialog)
        self.Enrollment_Number_label.setGeometry(QtCore.QRect(230, 80, 131, 41))
        self.Enrollment_Number_label.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Enrollment_Number_label.setObjectName("Enrollment_Number_label")
        self.Department = QtWidgets.QLabel(Profile_Window_Dialog)
        self.Department.setGeometry(QtCore.QRect(230, 200, 111, 41))
        self.Department.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Department.setObjectName("Department")
        self.Admission_YearLabel = QtWidgets.QLabel(Profile_Window_Dialog)
        self.Admission_YearLabel.setGeometry(QtCore.QRect(230, 140, 141, 41))
        self.Admission_YearLabel.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Admission_YearLabel.setObjectName("Admission_YearLabel")
        self.HOME_Label = QtWidgets.QPushButton(Profile_Window_Dialog)
        self.HOME_Label.setGeometry(QtCore.QRect(400, 360, 113, 32))
        self.HOME_Label.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.HOME_Label.setObjectName("HOME_Label")
        self.Account_Status_label = QtWidgets.QLabel(Profile_Window_Dialog)
        self.Account_Status_label.setGeometry(QtCore.QRect(220, 280, 141, 41))
        self.Account_Status_label.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Account_Status_label.setObjectName("Account_Status_label")
        self.Contact_label = QtWidgets.QLabel(Profile_Window_Dialog)
        self.Contact_label.setGeometry(QtCore.QRect(10, 300, 81, 21))
        self.Contact_label.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Contact_label.setObjectName("Contact_label")

        self.retranslateUi(Profile_Window_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Profile_Window_Dialog)

    def retranslateUi(self, Profile_Window_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Profile_Window_Dialog.setWindowTitle(_translate("Profile_Window_Dialog", "Dialog"))
        self.Name_Label.setText(_translate("Profile_Window_Dialog", "Name"))
        self.User_id_label.setText(_translate("Profile_Window_Dialog", "SJSU ID"))
        self.Email_Label.setText(_translate("Profile_Window_Dialog", "Email id"))
        self.Address_label.setText(_translate("Profile_Window_Dialog", "Address"))
        self.CourseName_label.setText(_translate("Profile_Window_Dialog", "Course Name :"))
        self.Enrollment_Number_label.setText(_translate("Profile_Window_Dialog", "Enrollment No.:"))
        self.Department.setText(_translate("Profile_Window_Dialog", "Department :"))
        self.Admission_YearLabel.setText(_translate("Profile_Window_Dialog", "Admission Year :"))
        self.HOME_Label.setText(_translate("Profile_Window_Dialog", "HOME"))
        self.Account_Status_label.setText(_translate("Profile_Window_Dialog", "Account Status :"))
        self.Contact_label.setText(_translate("Profile_Window_Dialog", "Mobile Phone"))
