# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sign_Up_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignUp_Dialog(object):
    def setupUi(self, SignUp_Dialog):
        SignUp_Dialog.setObjectName("SignUp_Dialog")
        SignUp_Dialog.resize(767, 494)
        SignUp_Dialog.setStyleSheet("QWidget {\n"
"    background-color: #73C2FB; /* Ice Blue*/\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}")
        self.Sign_Up = QtWidgets.QLabel(SignUp_Dialog)
        self.Sign_Up.setGeometry(QtCore.QRect(30, 30, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Sign_Up.setFont(font)
        self.Sign_Up.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Sign_Up.setObjectName("Sign_Up")
        self.AlreadySignIn = QtWidgets.QLabel(SignUp_Dialog)
        self.AlreadySignIn.setGeometry(QtCore.QRect(30, 80, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.AlreadySignIn.setFont(font)
        self.AlreadySignIn.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.AlreadySignIn.setObjectName("AlreadySignIn")
        self.Login = QtWidgets.QPushButton(SignUp_Dialog)
        self.Login.setGeometry(QtCore.QRect(210, 70, 113, 41))
        self.Login.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Login.setObjectName("Login")
        self.User_ID_Label = QtWidgets.QLabel(SignUp_Dialog)
        self.User_ID_Label.setGeometry(QtCore.QRect(20, 140, 121, 16))
        self.User_ID_Label.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.User_ID_Label.setTextFormat(QtCore.Qt.RichText)
        self.User_ID_Label.setScaledContents(True)
        self.User_ID_Label.setObjectName("User_ID_Label")
        self.EnterYourEmailUser = QtWidgets.QLineEdit(SignUp_Dialog)
        self.EnterYourEmailUser.setGeometry(QtCore.QRect(150, 130, 331, 31))
        self.EnterYourEmailUser.setStyleSheet("QLineEdit {\n"
"    background-color: transparent;\n"
"    border: 2px solid white;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"    color: yellow;\n"
"}")
        self.EnterYourEmailUser.setObjectName("EnterYourEmailUser")
        self.Name = QtWidgets.QLabel(SignUp_Dialog)
        self.Name.setGeometry(QtCore.QRect(20, 200, 121, 16))
        self.Name.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Name.setTextFormat(QtCore.Qt.RichText)
        self.Name.setScaledContents(True)
        self.Name.setObjectName("Name")
        self.EnterYourEmailUser_2 = QtWidgets.QLineEdit(SignUp_Dialog)
        self.EnterYourEmailUser_2.setGeometry(QtCore.QRect(150, 190, 331, 31))
        self.EnterYourEmailUser_2.setStyleSheet("QLineEdit {\n"
"    background-color: transparent;\n"
"    border: 2px solid white;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"    color: yellow;\n"
"}")
        self.EnterYourEmailUser_2.setObjectName("EnterYourEmailUser_2")
        self.EmailId_label = QtWidgets.QLabel(SignUp_Dialog)
        self.EmailId_label.setGeometry(QtCore.QRect(20, 260, 111, 16))
        self.EmailId_label.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.EmailId_label.setTextFormat(QtCore.Qt.RichText)
        self.EmailId_label.setScaledContents(True)
        self.EmailId_label.setObjectName("EmailId_label")
        self.EnterYourEmailUser_3 = QtWidgets.QLineEdit(SignUp_Dialog)
        self.EnterYourEmailUser_3.setGeometry(QtCore.QRect(150, 250, 331, 31))
        self.EnterYourEmailUser_3.setStyleSheet("QLineEdit {\n"
"    background-color: transparent;\n"
"    border: 2px solid white;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"    color: yellow;\n"
"}")
        self.EnterYourEmailUser_3.setObjectName("EnterYourEmailUser_3")
        self.Checkbox = QtWidgets.QCheckBox(SignUp_Dialog)
        self.Checkbox.setGeometry(QtCore.QRect(30, 370, 431, 20))
        self.Checkbox.setStyleSheet("Check Box{\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Checkbox.setObjectName("Checkbox")
        self.Submit = QtWidgets.QPushButton(SignUp_Dialog)
        self.Submit.setGeometry(QtCore.QRect(260, 420, 121, 41))
        self.Submit.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Submit.setObjectName("Submit")
        self.Image = QtWidgets.QLabel(SignUp_Dialog)
        self.Image.setGeometry(QtCore.QRect(510, 100, 211, 231))
        self.Image.setAutoFillBackground(False)
        self.Image.setStyleSheet("QLabel {\n"
"    background-color: #73C2FB; /* Ice Blue*/\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}")
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("Images/ChatGPT Image Apr 21, 2025, 12_09_12 AM.png"))
        self.Image.setScaledContents(True)
        self.Image.setObjectName("Image")
        self.Password_2 = QtWidgets.QLabel(SignUp_Dialog)
        self.Password_2.setGeometry(QtCore.QRect(20, 320, 111, 16))
        self.Password_2.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Password_2.setTextFormat(QtCore.Qt.RichText)
        self.Password_2.setScaledContents(True)
        self.Password_2.setObjectName("Password_2")
        self.EnterYourEmailUser_4 = QtWidgets.QLineEdit(SignUp_Dialog)
        self.EnterYourEmailUser_4.setGeometry(QtCore.QRect(150, 310, 331, 31))
        self.EnterYourEmailUser_4.setStyleSheet("QLineEdit {\n"
"    background-color: transparent;\n"
"    border: 2px solid white;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"    color: yellow;\n"
"}")
        self.EnterYourEmailUser_4.setObjectName("EnterYourEmailUser_4")

        self.retranslateUi(SignUp_Dialog)
        QtCore.QMetaObject.connectSlotsByName(SignUp_Dialog)

    def retranslateUi(self, SignUp_Dialog):
        _translate = QtCore.QCoreApplication.translate
        SignUp_Dialog.setWindowTitle(_translate("SignUp_Dialog", "Dialog"))
        self.Sign_Up.setText(_translate("SignUp_Dialog", "Sign Up"))
        self.AlreadySignIn.setText(_translate("SignUp_Dialog", "Already have account ?"))
        self.Login.setText(_translate("SignUp_Dialog", "Login"))
        self.User_ID_Label.setText(_translate("SignUp_Dialog", "SJSU Id"))
        self.Name.setText(_translate("SignUp_Dialog", "Name"))
        self.EmailId_label.setText(_translate("SignUp_Dialog", "Email Id"))
        self.Checkbox.setText(_translate("SignUp_Dialog", "By Signing up you agree to recieve updates and special offers"))
        self.Submit.setText(_translate("SignUp_Dialog", "Submit"))
        self.Password_2.setText(_translate("SignUp_Dialog", "Password"))
