# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Student_Dialog_Wallet.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Student_Wallet(object):
    def setupUi(self, Student_Wallet):
        Student_Wallet.setObjectName("Student_Wallet")
        Student_Wallet.resize(707, 639)
        Student_Wallet.setStyleSheet("QWidget {\n"
"    background-color: #73C2FB; /* Ice Blue*/\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}")
        self.Welcome = QtWidgets.QLineEdit(Student_Wallet)
        self.Welcome.setGeometry(QtCore.QRect(180, 80, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Welcome.setFont(font)
        self.Welcome.setStyleSheet("QLineEdit\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}")
        self.Welcome.setObjectName("Welcome")
        self.label = QtWidgets.QLabel(Student_Wallet)
        self.label.setGeometry(QtCore.QRect(300, 0, 81, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Spartan_Ride_App/SpartanLogo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Student_Wallet)
        self.label_2.setGeometry(QtCore.QRect(640, 10, 51, 51))
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Images/person.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.student_name = QtWidgets.QLabel(Student_Wallet)
        self.student_name.setGeometry(QtCore.QRect(490, 10, 60, 16))
        self.student_name.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}")
        self.student_name.setObjectName("student_name")
        self.Balamce = QtWidgets.QLabel(Student_Wallet)
        self.Balamce.setGeometry(QtCore.QRect(490, 40, 60, 16))
        self.Balamce.setStyleSheet("QLabel\n"
" {\n"
"    color: #FAFAD2;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"}")
        self.Balamce.setObjectName("Balamce")
        self.line = QtWidgets.QFrame(Student_Wallet)
        self.line.setGeometry(QtCore.QRect(0, 125, 701, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Student_pushbuttons = QtWidgets.QGroupBox(Student_Wallet)
        self.Student_pushbuttons.setGeometry(QtCore.QRect(0, 150, 701, 51))
        self.Student_pushbuttons.setTitle("")
        self.Student_pushbuttons.setObjectName("Student_pushbuttons")
        self.Wallet = QtWidgets.QPushButton(self.Student_pushbuttons)
        self.Wallet.setGeometry(QtCore.QRect(560, 10, 113, 32))
        self.Wallet.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Wallet.setObjectName("Wallet")
        self.RideHistory = QtWidgets.QPushButton(self.Student_pushbuttons)
        self.RideHistory.setGeometry(QtCore.QRect(390, 10, 113, 32))
        self.RideHistory.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.RideHistory.setObjectName("RideHistory")
        self.BookaRide = QtWidgets.QPushButton(self.Student_pushbuttons)
        self.BookaRide.setGeometry(QtCore.QRect(210, 10, 113, 32))
        self.BookaRide.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.BookaRide.setObjectName("BookaRide")
        self.Profile = QtWidgets.QPushButton(self.Student_pushbuttons)
        self.Profile.setGeometry(QtCore.QRect(40, 10, 113, 32))
        self.Profile.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Profile.setObjectName("Profile")
        self.Feedback = QtWidgets.QPushButton(Student_Wallet)
        self.Feedback.setGeometry(QtCore.QRect(10, 590, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setBold(True)
        font.setWeight(75)
        self.Feedback.setFont(font)
        self.Feedback.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Feedback.setObjectName("Feedback")
        self.SignOut = QtWidgets.QPushButton(Student_Wallet)
        self.SignOut.setGeometry(QtCore.QRect(610, 590, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setBold(True)
        font.setWeight(75)
        self.SignOut.setFont(font)
        self.SignOut.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.SignOut.setObjectName("SignOut")
        self.Wallet_2 = QtWidgets.QLabel(Student_Wallet)
        self.Wallet_2.setGeometry(QtCore.QRect(280, 210, 161, 61))
        self.Wallet_2.setStyleSheet("QLabel\n"
" {\n"
"    color: #191970;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}")
        self.Wallet_2.setScaledContents(True)
        self.Wallet_2.setObjectName("Wallet_2")
        self.groupbox = QtWidgets.QGroupBox(Student_Wallet)
        self.groupbox.setGeometry(QtCore.QRect(90, 270, 491, 271))
        self.groupbox.setStyleSheet("QGroupBox {\n"
"    background-color: #FFFACD;\n"
"    border: 2px solid #FFD700;\n"
"    border-radius: 10px;\n"
"    margin-top: 20px;\n"
"    font: bold 14px \'Segoe UI\';\n"
"    color: #0B1D3A;\n"
"}\n"
"\n"
"\n"
"")
        self.groupbox.setTitle("")
        self.groupbox.setObjectName("groupbox")
        self.CurrentBalanceLabel = QtWidgets.QPushButton(self.groupbox)
        self.CurrentBalanceLabel.setGeometry(QtCore.QRect(20, 50, 141, 41))
        self.CurrentBalanceLabel.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.CurrentBalanceLabel.setObjectName("CurrentBalanceLabel")
        self.PaymentMethod = QtWidgets.QPushButton(self.groupbox)
        self.PaymentMethod.setGeometry(QtCore.QRect(20, 100, 141, 41))
        self.PaymentMethod.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.PaymentMethod.setObjectName("PaymentMethod")
        self.PromoCode = QtWidgets.QPushButton(self.groupbox)
        self.PromoCode.setGeometry(QtCore.QRect(20, 160, 113, 32))
        self.PromoCode.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.PromoCode.setObjectName("PromoCode")
        self.BillingEmail = QtWidgets.QPushButton(self.groupbox)
        self.BillingEmail.setGeometry(QtCore.QRect(20, 210, 121, 41))
        self.BillingEmail.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.BillingEmail.setObjectName("BillingEmail")

        self.retranslateUi(Student_Wallet)
        QtCore.QMetaObject.connectSlotsByName(Student_Wallet)

    def retranslateUi(self, Student_Wallet):
        _translate = QtCore.QCoreApplication.translate
        Student_Wallet.setWindowTitle(_translate("Student_Wallet", "Dialog"))
        self.Welcome.setText(_translate("Student_Wallet", "Welcome to Spartan Ride"))
        self.student_name.setText(_translate("Student_Wallet", "Name"))
        self.Balamce.setText(_translate("Student_Wallet", "Balance"))
        self.Wallet.setText(_translate("Student_Wallet", "Wallet"))
        self.RideHistory.setText(_translate("Student_Wallet", "Ride History"))
        self.BookaRide.setText(_translate("Student_Wallet", "Book Ride"))
        self.Profile.setText(_translate("Student_Wallet", "Profile"))
        self.Feedback.setText(_translate("Student_Wallet", "Feedback"))
        self.SignOut.setText(_translate("Student_Wallet", "Sign Out"))
        self.Wallet_2.setText(_translate("Student_Wallet", "Wallet"))
        self.CurrentBalanceLabel.setText(_translate("Student_Wallet", "Current Balance :"))
        self.PaymentMethod.setText(_translate("Student_Wallet", "Payment Method :"))
        self.PromoCode.setText(_translate("Student_Wallet", "Promo Code :"))
        self.BillingEmail.setText(_translate("Student_Wallet", "Billing Email :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Student_Wallet = QtWidgets.QDialog()
    ui = Ui_Student_Wallet()
    ui.setupUi(Student_Wallet)
    Student_Wallet.show()
    sys.exit(app.exec_())
