# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Driver_MyLog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignUp_Dialog(object):
    def setupUi(self, SignUp_Dialog):
        SignUp_Dialog.setObjectName("SignUp_Dialog")
        SignUp_Dialog.resize(793, 545)
        SignUp_Dialog.setStyleSheet("QWidget {\n"
"    background-color: #73C2FB; /* Ice Blue*/\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}")
        self.Login = QtWidgets.QPushButton(SignUp_Dialog)
        self.Login.setGeometry(QtCore.QRect(60, 120, 113, 41))
        self.Login.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Login.setObjectName("Login")
        self.Name = QtWidgets.QLabel(SignUp_Dialog)
        self.Name.setGeometry(QtCore.QRect(50, 190, 311, 31))
        self.Name.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Name.setTextFormat(QtCore.Qt.RichText)
        self.Name.setScaledContents(True)
        self.Name.setObjectName("Name")
        self.Login_2 = QtWidgets.QPushButton(SignUp_Dialog)
        self.Login_2.setGeometry(QtCore.QRect(250, 120, 113, 41))
        self.Login_2.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Login_2.setObjectName("Login_2")
        self.Login_3 = QtWidgets.QPushButton(SignUp_Dialog)
        self.Login_3.setGeometry(QtCore.QRect(440, 120, 113, 41))
        self.Login_3.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Login_3.setObjectName("Login_3")
        self.Login_4 = QtWidgets.QPushButton(SignUp_Dialog)
        self.Login_4.setGeometry(QtCore.QRect(630, 120, 113, 41))
        self.Login_4.setStyleSheet("QPushButton {\n"
"    background-color: #FAFAD2; /* Gold */\n"
"    color: #0B1D3A;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #FAFAD2;\n"
"}")
        self.Login_4.setObjectName("Login_4")
        self.Name_2 = QtWidgets.QLabel(SignUp_Dialog)
        self.Name_2.setGeometry(QtCore.QRect(270, 70, 241, 31))
        self.Name_2.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.Name_2.setTextFormat(QtCore.Qt.RichText)
        self.Name_2.setScaledContents(True)
        self.Name_2.setObjectName("Name_2")
        self.EmailID_5 = QtWidgets.QLabel(SignUp_Dialog)
        self.EmailID_5.setGeometry(QtCore.QRect(570, 20, 91, 16))
        self.EmailID_5.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.EmailID_5.setTextFormat(QtCore.Qt.RichText)
        self.EmailID_5.setScaledContents(True)
        self.EmailID_5.setObjectName("EmailID_5")
        self.label = QtWidgets.QLabel(SignUp_Dialog)
        self.label.setGeometry(QtCore.QRect(360, 20, 61, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("SpartanLogo_small.png"))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(SignUp_Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(50, 270, 691, 192))
        self.tableWidget.setRowCount(8)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(127)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(28)
        self.label_2 = QtWidgets.QLabel(SignUp_Dialog)
        self.label_2.setGeometry(QtCore.QRect(650, 20, 71, 16))
        self.label_2.setObjectName("label_2")
        self.EmailID_8 = QtWidgets.QLabel(SignUp_Dialog)
        self.EmailID_8.setGeometry(QtCore.QRect(50, 480, 141, 16))
        self.EmailID_8.setStyleSheet("QLabel {\n"
"    color: #FAFAD2;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}")
        self.EmailID_8.setTextFormat(QtCore.Qt.RichText)
        self.EmailID_8.setScaledContents(True)
        self.EmailID_8.setObjectName("EmailID_8")
        self.lineEdit = QtWidgets.QLineEdit(SignUp_Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(180, 480, 113, 21))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(SignUp_Dialog)
        QtCore.QMetaObject.connectSlotsByName(SignUp_Dialog)

    def retranslateUi(self, SignUp_Dialog):
        _translate = QtCore.QCoreApplication.translate
        SignUp_Dialog.setWindowTitle(_translate("SignUp_Dialog", "Dialog"))
        self.Login.setText(_translate("SignUp_Dialog", "My Profile"))
        self.Name.setText(_translate("SignUp_Dialog", "<html><head/><body><p><span style=\" font-size:24pt;\">My Log</span></p></body></html>"))
        self.Login_2.setText(_translate("SignUp_Dialog", "My Routes"))
        self.Login_3.setText(_translate("SignUp_Dialog", "My Log"))
        self.Login_4.setText(_translate("SignUp_Dialog", "Notifications"))
        self.Name_2.setText(_translate("SignUp_Dialog", "<html><head/><body><p><span style=\" font-size:18pt;\">Welcome to Spartan Ride</span></p></body></html>"))
        self.EmailID_5.setText(_translate("SignUp_Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:400; color:#0c0805;\">Name</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SignUp_Dialog", "Day"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SignUp_Dialog", "Route ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("SignUp_Dialog", "Start Time"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("SignUp_Dialog", "End Time"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("SignUp_Dialog", "Working Hours"))
        self.label_2.setText(_translate("SignUp_Dialog", "John Stein"))
        self.EmailID_8.setText(_translate("SignUp_Dialog", "<html><head/><body><p><span style=\" font-weight:400;\">My Salary (USD)</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignUp_Dialog = QtWidgets.QDialog()
    ui = Ui_SignUp_Dialog()
    ui.setupUi(SignUp_Dialog)
    SignUp_Dialog.show()
    sys.exit(app.exec_())
